<?xml version="1.0" encoding="UTF-8"?>
<testng-results total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-06-04T03:44:02Z" name="Suite 1" finished-at="2021-06-04T03:44:20Z" duration-ms="18659">
    <groups>
    </groups>
    <test started-at="2021-06-04T03:44:02Z" name="TEST_1" finished-at="2021-06-04T03:44:20Z" duration-ms="18659">
      <class name="com.changefinancial.TestCases.T_5_ChangePasswordWithCorrectPassword">
        <test-method signature="changePassword()[pri:0, instance:com.changefinancial.TestCases.T_5_ChangePasswordWithCorrectPassword@31ff6309]" started-at="2021-06-04T15:44:02Z" name="changePassword" finished-at="2021-06-04T15:44:19Z" duration-ms="17051" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [1Your password has been updated successfully.] but found [Your password has been updated successfully.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [1Your password has been updated successfully.] but found [Your password has been updated successfully.]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:179)
	at com.changefinancial.utils.AssertLocal.assertEquals(AssertLocal.java:15)
	at com.changefinancial.TestCases.T_5_ChangePasswordWithCorrectPassword.changePassword(T_5_ChangePasswordWithCorrectPassword.java:42)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- changePassword -->
        <test-method is-config="true" signature="testMethodEnd()[pri:0, instance:com.changefinancial.TestCases.T_5_ChangePasswordWithCorrectPassword@31ff6309]" started-at="2021-06-04T15:44:19Z" name="testMethodEnd" finished-at="2021-06-04T15:44:20Z" duration-ms="1166" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testMethodEnd -->
      </class> <!-- com.changefinancial.TestCases.T_5_ChangePasswordWithCorrectPassword -->
    </test> <!-- TEST_1 -->
  </suite> <!-- Suite 1 -->
</testng-results>
